spring:
  application:
    name: fhir-json-converter

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=10m

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

fhir:
  converter:
    templates-path: classpath:templates/
    validation:
      enabled: true
      strict: false
    output-format: json
    pretty-print: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.fhirconverter: DEBUG
    ca.uhn.fhir: INFO
